---
apiVersion: 1
kind: Secret
metadata: 
    name: {{ include "go-rest-api.fullname" . }}-secrets
type: Opaque
data: 
    GO_REST_API_KEY: "{{ .Values.gorestapiSettings.gorestAPIKEY | default "" | b64enc }}"
    GO_REST_API_ID: "{{ .Values.gorestapiSettings.gorestAPIID | default "" | b64enc }}"